const questions = [
  {
    id: 1,
    topic: "basic",
    title: "Program to print 'hello world'",
    description: "Write a program to print 'hello world'",
    diffLevel: "very easy",
    testCases: [
      {
        inputFront: "",
        input: "",
        output: "hello world",
        testCase: "Test Case 1",
        testCaseDescription: "Test Case 1",
        testCaseNumber: 1,
      },
    ],
  },
  {
    id: 2,
    topic: "basic",
    title: "Program to Swap two Numbers",
    description:
      "Your task is to input two numbers from the user, swap them and print their values.",
    diffLevel: "very easy",
    testCases: [
      {
        inputFront: "a = 10, b = 20",
        input: "10 20",
        output: "20 10",
        explaination: "After swapping a = 20, b = 10",
        testCase: "Test Case 1",
        testCaseDescription: "Test Case 1",
        testCaseNumber: 1,
      },
      {
        inputFront: "a = 120, b = 50",
        input: "120 50",
        output: "50 120",
        explaination: "After swapping a = 50, b = 120",
        testCase: "Test Case 2",
        testCaseDescription: "Test Case 2",
        testCaseNumber: 2,
      },
    ],
  },
  {
    id: 3,
    topic: "loops",
    title: "Print alternate numbers",
    description: "Print alternate numbers from 1 to n",
    diffLevel: "easy",
    testCases: [
      {
        input: "5",
        output: "1 3 5 7 9",
        testCase: "Test Case 1",
        testCaseDescription: "Test Case 1",
        testCaseNumber: 1,
      },
      {
        input: "10",
        output: "1 3 5 7 9 11 13 15 17 19",
        testCase: "Test Case 2",
        testCaseDescription: "Test Case 2",
        testCaseNumber: 2,
      },
      {
        input: "15",
        output: "1 3 5 7 9 11 13 15 17 19 21 23 25 27 29",
        testCase: "Test Case 3",
        testCaseDescription: "Test Case 3",
        testCaseNumber: 3,
      },
    ],
  },
  {
    id: 4,
    topic: "conditionals",
    title: "Eligibility for vote",
    description:
      "Take Raji's age as an input then print 'eligible' if its greater than or equal to 18, else print 'not eligible'",
    diffLevel: "easy",
    testCases: [
      {
        input: "5",
        output: "'not eligible'",
        explaination: "Age is less than 18, so raju cant vote",
        testCase: "Test Case 1",
        testCaseDescription: "Test Case 1",
        testCaseNumber: 1,
      },
      {
        input: "18",
        output: "'eligible'",
        explaination: "Age is equal to 18, so raju can vote",
        testCase: "Test Case 2",
        testCaseDescription: "Test Case 2",
        testCaseNumber: 2,
      },
      {
        input: "43",
        output: "'eligible'",
        explaination: "Age is far greater than 18, so raju can vote",
        testCase: "Test Case 3",
        testCaseDescription: "Test Case 3",
        testCaseNumber: 3,
      },
    ],
  },
  {
    id: 5,
    topic: "strings",
    title: "Palindrome",
    description:
      "Print 'palindrome' if the string is a palindrome, else print 'not palindrome'",
    diffLevel: "easy",
    testCases: [
      {
        input: "madam",
        output: "'palindrome'",
        explaination: "'madam' spelled backwards is also 'madam'",
        testCase: "Test Case 1",
        testCaseDescription: "Test Case 1",
        testCaseNumber: 1,
      },
      {
        input: "miss cse",
        output: "'not palindrome'",
        explaination: "'miss cse' spelled backwards is not 'esc ssim'",
        testCase: "Test Case 2",
        testCaseDescription: "Test Case 2",
        testCaseNumber: 2,
      },
      {
        input: "malayalam",
        output: "'palindrome'",
        explaination: "'malayalam' spelled backwards is also 'malayalam'",
        testCase: "Test Case 3",
        testCaseDescription: "Test Case 3",
        testCaseNumber: 3,
      },
    ],
  },
  {
    id: 6,
    topic: "arrays",
    title: "Program to find the average and largest number in an array",
    description:
      "Write a program to find the average and largest number in an array",
    diffLevel: "easy",
    testCases: [
      {
        input: [4, 2, 1, 5, 3],
        output: '"average: 3.0, largest: 5"',
        expected: true,
        explaination: "average: 4+2+1+5+3 / 5 = 3.0, largest: 5",
        testCase: "Test Case 1",
        testCaseDescription: "Test Case 1",
        testCaseNumber: 1,
      },
      {
        input: [7, 4, 9, 8, 6, 10, 3, 2, 1, 5],
        output: '"average: 5.5, largest: 10"',
        expected: true,
        testCase: "Test Case 2",
        testCaseDescription: "Test Case 2",
        testCaseNumber: 2,
      },
      {
        input: [
          1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        ],
        output: 20,
        expected: true,
        testCase: "Test Case 3",
        testCaseDescription: "Test Case 3",
        testCaseNumber: 3,
      },
    ],
  },
  {
    id: 7,
    topic: "loops",
    title: "Program to print n fibonacci numbers",
    description: "Print n fibonacci numbers",
    diffLevel: "medium",
    testCases: [
      {
        input: 7,
        output: [1, 1, 2, 3, 5, 8, 13],
        expected: true,
        testCase: "Test Case 1",
        testCaseDescription: "Test Case 1",
        testCaseNumber: 1,
      },
      {
        input: 10,
        output: [1, 1, 2, 3, 5, 8, 13, 21, 34, 55],
        expected: true,
        testCase: "Test Case 2",
        testCaseDescription: "Test Case 2",
        testCaseNumber: 2,
      },
      {
        input: 20,
        output: [
          1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597,
          2584, 4181,
        ],
        expected: true,
        testCase: "Test Case 3",
        testCaseDescription: "Test Case 3",
        testCaseNumber: 3,
      },
    ],
  },
  {
    id: 8,
    topic: "strings",
    title: "Convert binary to decimal",
    description:
      "Convert binary to decimal. For example, 1010 is converted to 10",
    diffLevel: "medium",
    testCases: [
      {
        input: "1010",
        output: "10",
        explaination: "1010 = 1*2^3 + 0*2^2 + 1*2^1 + 0*2^0 = 10",
        testCase: "Test Case 1",
        testCaseDescription: "Test Case 1",
        testCaseNumber: 1,
      },
      {
        input: "1111",
        output: "15",
        explaination: "1111 = 1*2^4 + 1*2^3 + 1*2^2 + 1*2^1 + 1*2^0 = 15",
        testCase: "Test Case 2",
        testCaseDescription: "Test Case 2",
        testCaseNumber: 2,
      },
      {
        input: "10001",
        output: "21",
        explaination:
          "10001 = 1*2^5 + 0*2^4 + 0*2^3 + 0*2^2 + 0*2^1 + 1*2^0 = 21",
        testCase: "Test Case 3",
        testCaseDescription: "Test Case 3",
        testCaseNumber: 3,
      },
    ],
  },
];

// export default questions;
